#!/usr/bin/env perl

### 把 markdown 文档中引用的图片用 base64 编码后再塞回去，使其不再需要引用图片。需要 imagemagick。

use v5.12;
use utf8;
use Encode qw/decode_utf8/;
binmode STDOUT, ':encoding(utf8)';

sub process_image
{
	$_ = shift;
	if (/\.gif$/) {
		"data:image/gif;base64," .
		qx {
		convert -fuzz 15% -layers Optimize \Q$_\E - | base64 | tr -d '\n'
		}
	} else {
		"data:image/jpeg;base64," .
		qx {
		convert -resize \Q640x480>\E -strip -quality 75% \Q$_\E jpeg:- | base64 | tr -d '\n'
		}
	}
}

my @lines = map { decode_utf8 $_ } (<>);

my @title_count;
say "# 目录";
for (@lines) {
    if (/^(#+)\s*(.*)$/) {
        my ($level, $title) = (length($1), $2);
        my $indent = "  " x $level;
        my $url = $title;
        $url =~ s/[^_[:^punct:]]//g;
        $url =~ s/[[:space:]]/-/g;
        @title_count = splice @title_count, 0, $level;
        $title_count[$level - 1] += 1;
        my $index = join ".", @title_count;
        say "$indent+ $index [$title](#$url)";
    }
}

say "";

for my $line (@lines) {
	for ($line =~ /!\[[^\]]*\]\([^)]*\)/g) {
		my ($mark, $desc, $file) = /(!\[([^\]]*)\]\(([^)]*)\))/;
		$file = process_image $file;
		$line =~ s/\Q$mark\E/![]($file)/;
	}
	print $line;
}
